name: CI & Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@v1.1.5
        with:
          switches: -avz --delete
          path: ./
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_path: ${{ secrets.VPS_REMOTE_PATH }}
          ssh_private_key: ${{ secrets.VPS_SSH_KEY }}
          ssh_port: ${{ secrets.VPS_SSH_PORT }}
          exclude: |
            .git/
            .github/
            vendor/
      - name: Run post-deploy commands
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd ${{ secrets.VPS_REMOTE_PATH }}
            composer install --no-dev --optimize-autoloader
      - name: Completed
        run: echo "Deployment to VPS completed successfully"