name: CI & Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
            
      # Preparar a chave SSH
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: ${{ secrets.VPS_HOST }}
          if_key_exists: replace
          
      # Adicionar o host conhecido de forma segura
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
      # Deploy com rsync modificado para preservar diretórios de dados
      - name: Deploy with rsync
        run: |
          rsync -avz \
          --exclude=".git/" \
          --exclude=".github/" \
          --exclude=".gitignore" \
          --exclude="README.md" \
          --exclude=".env" \
          --exclude=".env.example" \
          --exclude="logs/" \
          --exclude="temp/" \
          --exclude="pdfs/" \
          --exclude="database/" \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_REMOTE_PATH }} \
          -e "ssh -p ${{ secrets.VPS_SSH_PORT }} -o StrictHostKeyChecking=no"
      
      - name: Completed
        run: echo "Deployment to VPS completed successfully"